/**
 * Presets tuned for perceptually distinct beach scenarios.
 * Values map to UI sliders (0–100 unless noted).
 */
export const PRESETS = [
  {
    id: 'dawn-shore',
    name: 'Amanecer en la orilla',
    description: 'Muy calmado. Olas largas, espaciadas, poco phaser.',
    mode: 'beach',
    autoRotate: true,
    values: {
      calmness: 48,
      waveDuration: 45,
      waveSpeed: 14,
      waveInterval: 22,
      phaserRate: 6,
      phaserDepth: 28,
      phaserMix: 22,
      rotationSpeed: 8,
      manualYaw: 0,
      waveSpread: 28,
      waterDepth: 0,
      masterVolume: 68,
    },
  },
  {
    id: 'gentle-lapping',
    name: 'Lameteo suave',
    description: 'Pequeñas olas cerca del pie. Ritmo regular y claro.',
    mode: 'beach',
    autoRotate: false,
    values: {
      calmness: 62,
      waveDuration: 18,
      waveSpeed: 32,
      waveInterval: 9,
      phaserRate: 14,
      phaserDepth: 42,
      phaserMix: 38,
      rotationSpeed: 0,
      manualYaw: 0,
      waveSpread: 22,
      waterDepth: 8,
      masterVolume: 72,
    },
  },
  {
    id: 'long-swell',
    name: 'Oleaje largo (meditativo)',
    description: 'Una ola tarda mucho en cruzar el arco. Ideal para rotación lenta.',
    mode: 'beach',
    autoRotate: true,
    values: {
      calmness: 52,
      waveDuration: 55,
      waveSpeed: 10,
      waveInterval: 28,
      phaserRate: 8,
      phaserDepth: 35,
      phaserMix: 30,
      rotationSpeed: 12,
      manualYaw: 0,
      waveSpread: 45,
      waterDepth: 0,
      masterVolume: 70,
    },
  },
  {
    id: 'sheltered-bay',
    name: 'Bahía resguardada',
    description: 'Wash envolvente 360°, baja intensidad, sensación de cala.',
    mode: 'bay',
    autoRotate: true,
    values: {
      calmness: 58,
      waveDuration: 32,
      waveSpeed: 18,
      waveInterval: 14,
      phaserRate: 10,
      phaserDepth: 38,
      phaserMix: 35,
      rotationSpeed: 15,
      manualYaw: 0,
      waveSpread: 40,
      waterDepth: 0,
      masterVolume: 65,
    },
  },
  {
    id: 'light-surf',
    name: 'Surf ligero',
    description: 'Más energía en la espuma. Rompiente audible pero no agresiva.',
    mode: 'beach',
    autoRotate: true,
    values: {
      calmness: 78,
      waveDuration: 22,
      waveSpeed: 38,
      waveInterval: 7,
      phaserRate: 18,
      phaserDepth: 58,
      phaserMix: 52,
      rotationSpeed: 20,
      manualYaw: 0,
      waveSpread: 30,
      waterDepth: 5,
      masterVolume: 74,
    },
  },
  {
    id: 'wading-in',
    name: 'Entrando al agua',
    description: 'Orilla con pies mojados. Transición hacia el subsurface.',
    mode: 'beach',
    autoRotate: false,
    values: {
      calmness: 65,
      waveDuration: 24,
      waveSpeed: 28,
      waveInterval: 11,
      phaserRate: 12,
      phaserDepth: 45,
      phaserMix: 40,
      rotationSpeed: 0,
      manualYaw: 0,
      waveSpread: 32,
      waterDepth: 42,
      masterVolume: 70,
    },
  },
  {
    id: 'deep-wade',
    name: 'Agua hasta las rodillas',
    description: 'Mayor muffled underwater, burbujas y reverb.',
    mode: 'beach',
    autoRotate: true,
    values: {
      calmness: 60,
      waveDuration: 26,
      waveSpeed: 22,
      waveInterval: 13,
      phaserRate: 9,
      phaserDepth: 30,
      phaserMix: 25,
      rotationSpeed: 10,
      manualYaw: 0,
      waveSpread: 38,
      waterDepth: 72,
      masterVolume: 68,
    },
  },
  {
    id: 'contemplation-360',
    name: 'Contemplación 360°',
    description: 'Giro muy lento en bahía. Olas amplias que te rodean.',
    mode: 'bay',
    autoRotate: true,
    values: {
      calmness: 55,
      waveDuration: 38,
      waveSpeed: 16,
      waveInterval: 18,
      phaserRate: 11,
      phaserDepth: 40,
      phaserMix: 36,
      rotationSpeed: 6,
      manualYaw: 0,
      waveSpread: 50,
      waterDepth: 0,
      masterVolume: 66,
    },
  },
];

export function getPresetById(id) {
  return PRESETS.find((p) => p.id === id) ?? null;
}
